apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: gcr.io/xxxxx/xxxxx:latest
          ports:
            - containerPort: 8080
