apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudrun-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: "terraform"
    spec:
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/your-image:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
